server:
  http_listen_port: {%HTTPPORT%}
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://{%LOKI_LISTEN_ADDRESS%}:{%LOKI_LISTEN_PORT%}/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      labels:
        job: systemd-journal
      max_age: 24h
      path: /var/log/journal

    relabel_configs:
      - source_labels:
          - __journal__systemd_unit
        target_label: systemd_unit
      - source_labels:
          - __journal__systemd_user_unit
        target_label: systemd_user_unit
      - source_labels:
          - __journal__hostname
        target_label: nodename
      - source_labels:
          - __journal_syslog_identifier
        target_label: syslog_identifier
      - source_labels:
          - __journal__transport
        target_label: transport

    pipeline_stages:
      - template:
          source: level
          template: '{{ if eq .Value "0" }}{{ Replace .Value "0" "emerg" 1 }}{{ else if eq .Value "1" }}{{ Replace .Value "1" "alert" 1 }}{{ else if eq .Value "2" }}{{ Replace .Value "2" "crit" 1 }}{{ else if eq .Value "3" }}{{ Replace .Value "3" "err" 1 }}{{ else if eq .Value "4" }}{{ Replace .Value "4" "warning" 1 }}{{ else if eq .Value "5" }}{{ Replace .Value "5" "notice" 1 }}{{ else if eq .Value "6" }}{{ Replace .Value "6" "info" 1 }}{{ else if eq .Value "7" }}{{ Replace .Value "7" "debug" 1 }}{{ end }}'
      - labels:
          level:
      # 过滤系统服务日志
      - drop:
          source: syslog_identifier
          expression: ".*{%EXCLUDE_SERVICES%}.*"
      - match:
          selector: '{systemd_unit="jsy-archiver.service"}'
          action: keep
          stages:
            - regex:
                expression: "{%JSY_ARCHIVER_LOG_REGEX%}"
            - labels:
                level:
                archiver_job:
                conclusion:
                duration:
      - match:
          selector: '{systemd_unit="wind-importer.service"}'
          action: keep
          stages:
            - regex:
                expression: "{%WIND_IMPORTER_LOG_REGEX%}"
            - labels:
                level:
                importer_job:
                conclusion:
                duration:
      - match:
          selector: '{systemd_unit="jsy-importer.service"}'
          action: keep
          stages:
            - regex:
                expression: "{%JSY_IMPORTER_LOG_REGEX%}"
            - labels:
                level:
                importer_job:
                conclusion:
                duration:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: sbcode
          __path__: /var/log/nginx/*log
    pipeline_stages:
    - match:
        selector: '{job="nginx"}'
        stages:
        - regex:
            expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
        - labels:
            #remote_addr:
            #remote_user:
            #time_local:
            method:
            #request:
            #protocol:
            status:
            #body_bytes_sent:
            #http_referer:
            #http_user_agent: