version: "3"
services:
  nas-tools:
    image: hsuyelin/nas-tools:latest
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/config/nastools:/config
      - /volume1/nastools/Anime:/Anime
      - /volume1/nastools/Movie:/Movie
      - /volume1/nastools/TV:/TV
    environment:
      - PUID=1000 # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=10 # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=022 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=true # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=true # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools

  qbittorrent-nox:
    container_name: qbittorrent-nox
    environment:
      #- PAGID=10000
      - PGID=1000
      - PUID=10
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=5.0.2-1
      - QBT_WEBUI_PORT=18080
      - TZ=CTS
      - UMASK=022
    image: qbittorrentofficial/qbittorrent-nox:5.0.2-1
    ports:
      # for bittorrent traffic
      - 6881:6881/tcp
      - 6881:6881/udp
      # for WebUI
      - 18080:18080/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - /volume1/docker/config/qbittorrent-nox:/config
      - /volume1/Video:/downloads
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=10
      - TZ=CTS
    volumes:
      - /volume1/docker/config/emby:/config
      - /volume1/Video/TV:/data/tvshows
      - /volume1/Video/Movie:/data/movies
      - /volume1/Video/Anime:/data/anime
    ports:
      - 8096:8096
      - 8920:8920 #optional
    # devices:
    #   # - /dev/dri:/dev/dri #optional
    #   # - /dev/vchiq:/dev/vchiq #optional
    #   # - /dev/video10:/dev/video10 #optional
    #   # - /dev/video11:/dev/video11 #optional
    #   # - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
  chinesesubfinder:
    image: wwfnle/chinesesubfinder:latest
    volumes:
      - /volume1/docker/config/chinesesubfinder:/config # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /volume1/Video/TV:/media/TV # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - /volume1/Video/Movie:/media/Movie
      - /volume1/Video/Anime:/media/Anime
      - /volume1/docker/config/chinesesubfinder/browser:/root/.cache/rod/browser # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=1000
      - PGID=10
      - PERMS=true # 是否重设/media权限
      - TZ=Asia/Shanghai # 时区
      - UMASK=022 # 权限掩码
    restart: always
    network_mode: bridge
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    ports:
      - 19035:19035 # 从0.20.0版本开始，通过webui来设置
      - 19037:19037 # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
      driver: "json-file"
      options:
        max-size: "100m" # 限制docker控制台日志大小，可自行调整
