---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- NetWork:
    - OpenWrt:
        href: http://192.168.31.3/cgi-bin/luci/admin/services/openclash/client
        description: OpenWrt
        ping: 192.168.31.3
    - OpenClash:
        href: http://192.168.31.3:9090/ui/yacd/?hostname=192.168.31.3&port=9090&secret=123456#/proxies
        description: OpenClash
    - PVE:
        href: https://192.168.31.2:8006/
        description: PVE
        widget:
            type: proxmox
            url: https://192.168.31.2:8006
            username: api@pam!homepage
            password: 82cb60ea-eb26-4203-a7fc-3780f594825e
            node: pve
    - Router:
        href: http://192.168.31.174/
        description: Router
        ping: 192.168.31.174

- Data:
    - NasTools:
        href: http://192.168.31.110:3000/
        description: NasTools
    - Emby:
        href: http://192.168.31.110:8096/
        description: NasTools
    - qBittorrent:
        href: http://192.168.31.110:18080/
        description: qBittorrent
    - jackett:
        href: http://192.168.31.4:9117/UI/Dashboard
        description: Jackett
    - Alist:
        href: http://192.168.31.4:5244/
        description: Alist
    - AliyunWebdav:
        href: http://192.168.31.4:8080/
        description: Aliyun

- Docker:
    - Portainer R:
        href: http://192.168.31.4:9000/#!/home
        description: Portainer
        ping: 192.168.31.4
        widget:
            type: portainer
            url: http://192.168.31.4:9000
            env: 2
            key: ptr_+I9YCesJjEkKbsZD26LRObuowAIct34yp1l33h43guw=

- Monitor:
    - Grafana:
        href: http://192.168.31.4:3000/?orgId=1
        description: Grafana
    - Prometheus:
        href: http://192.168.31.4:9090
        widget:
            type: prometheus
            url: http://192.168.31.4:9090
- Other:
    - Calender:
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            timezone: America/Los_Angeles
    - HomeAssistant:
        href: http://192.168.31.4:8123
        widget:
            type: homeassistant
            url: http://192.168.31.4:8123
            key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1YTk4NjlhYTUxNzI0NGNhYTA3MTQyNWM5ZjlmYmQ3MiIsImlhdCI6MTcwOTY1MDY2OCwiZXhwIjoyMDI1MDEwNjY4fQ.Sr9T10b_NBxo-zk6HfY31wBy3A1wAAaDUhE538qPpNs
